### ISSUE TITLE
Client ID tracking is node-local

### ISSUE THREAD

**Issue by dcovello** [rabbitmq/rabbitmq-mqtt#91] opened 2016-07-26 21:09 UTC
**Description of Issue**
It looks like RabbitMQ MQTTT brokers will properly handle multiple mqtt connections with duplicate client id's by disconnecting the older connection, establishing the newer one and logging the following message :

> MQTT disconnecting duplicate client id ""

_My current RabbitMQ setup involves mosquitto MQTT clients connecting to a HAProxy Loadbalancer which balances connections between the RabbitMQ-MQTT brokers on a rabbitmq cluster._ 

However, it does not seem to be disconnecting duplicate client ID's across a clustered RabbitMQ setup. I am currently able to connect multiple mqtt clients with the same client ID to a rabbitMQ Cluster as long as they are not connected to the same node.

This is currently a problem in my scenario where my mosquitto clients consistently experience unstable network conditions which will cause them to lose internet connection and reconnect later on with the same client ID. If this reconnection occurs within the keepalive interval and is balanced to a different rabbitmq node I will have two connections with same client ID existing until the keepalive interval expires and kills the initial connection.

Doing some research into this issue I found the following chat from 2014/15 which describes someone else experiencing this exact scenario :
https://groups.google.com/forum/#!topic/rabbitmq-users/ecLWQhHBg1g

However following up on Michael Klishins final response I looked through the changelog and the rabbitmq issue history and was not able to find any documentation referencing this issue.  I then recreated the scenario myself with a test environment using the versions listed below. 

Was the issue fixed somewhere that I somehow overlooked in the newer versions of rabbitmq?

**Versions**
HA-Proxy version 1.5.14 2015/07/02
Mosquitto 1.4.9
RabbitMQ 3.5.6
Erlang 17.5

**Comment by michaelklishin** [comment] 2016-07-27 07:14
Correct, client IDs are checked from a node-local source. https://github.com/rabbitmq/rabbitmq-server/issues/500 will make tracking cluster-wide much easier.

**Comment by michaelklishin** [comment] 2016-12-01 13:30
Key open question in this issue is where to store client ID in the connection tracking tables. We don't want them to be too protocol-specific but we also would rather avoid reinventing the same idea with a separate set of tables. Plus we want efficient querying. So this may be harder than it seems even in master.

**Comment by et1975** [comment] 2017-03-30 19:53
This is quite a bit an issue for us at the moment, is there an update? Any suggestions/workarounds?

**Comment by michaelklishin** [comment] 2017-03-30 20:00
There are no workarounds other than: prevent your clients from using duplicate client IDs.

Sorry but this feature is not a priority and will most likely only appear in 3.8.0 in the 2nd half of this year.

**Comment by et1975** [comment] 2017-03-30 20:34
>prevent your clients from using duplicate client IDs.

Just to clarify, there are not duplicates, the IDs uniquely identify clients for persistent session and QoS 1.

Am I understanding this correctly: load-balancing of persistent MQTT connections is not currently possible, unless it's implemented in a way that ties specific client to specific cluster node, permanently?

**Comment by michaelklishin** [comment] 2017-03-30 20:35
RabbitMQ does not load balance connections. Any client can connect to any node, publish to any node, consume from any node. For better or worse that's what the messaging protocols we support imply. Things are somewhat different for queues but if you want to load balance connections, use a load balancer.

**Comment by et1975** [comment] 2017-03-30 20:41
Quoting the OP here:
> setup involves mosquitto MQTT clients connecting to a HAProxy Loadbalancer which balances connections between the RabbitMQ-MQTT brokers on a rabbitmq cluster.

So yeah, we are balancing with a balancer ;)

The issue is, the same client ends up connecting to a different node, and that node does't take over keepalive responsibilities. At somepoint, the original node sends LastWillAndTestament, even though the connection to the cluster has been reestablished (but on a new node).

**Comment by michaelklishin** [comment] 2017-03-30 20:44
I'm not sure what you meay by "doesn't take over keepalive responsibilities". Keepalives and [gone connection tracking](http://www.rabbitmq.com/heartbeats.html) is a responsibility of the node that connection was to. Use a lower keepalive value. That has nothing to do with this issue and this is not a support forum, so if you have further questions, please take it to rabbitmq-users.

**Comment by emre141** [comment] 2018-11-30 13:11
Hi Michael,

I have the same issue exactly one to one .As mentioned user et1975 issue our case as below.But i do not understand the point this issue is open would be able to resolve in 3.8.0 milestone 2 or our issue is not releated the opened issue #152 ?

1.When i saw there is more than one connection with one consumer to the broker cluster than i publish several message like 10 message approximately 3 or 5 message consume but other retain unack state in channel and queue.First one why not all of them did not consumed
2. My ELB connection health check as below.So in this setting when i prevent to brain stream ( I assume while the cluster peering does not complete yet consumer reconnect to the broker behind load balancer that redirect to the each node and consumer connected twices).How can i fix them either on consumer client configuration or load balancer?

Ping Target	
TCP:1883
Timeout	3 seconds
Interval	30 seconds
Unhealthy threshold	10
Healthy threshold	2

Our cluster vhost policy as below

ha-mode:	all
ha-sync-mode:	automatic
queue-master-locator:	random

Hipe Disable 
We do not use lazy queue

- Our pub/sub model now Multiple mqtt publisher but one consumer to the rabbitmq cluster behind AWS ELB Load balancer.

- When i restart an individual node in the cluster consumer reconnect again one connection and consume each message correctly 

- But when i restart all node inside cluster the consumer reconnect each node separately ( we are using still one consumer ) than i send several message with publishers a few message unack and keep in the queue.And than cluster come back ready as soon but all duplicated connection retain we are waiting more than 15 minutes the connection still retain and when i send several message with publisher some message did not consume and keep in the unack state.

- I am using defalt setting ( mqtt tcp keepalive default so i did not add any config parameter i do not know what is the default parameter tcp keepalive) .Bu my load balancer health check as above.
- My consumer has Qos1 and cleansession = false 
- We are using durable queue so if the consumer disconnect queue is still on there
- We are using Queue mirroring

**Comment by michaelklishin** [comment] 2019-04-13 19:12
An update to this: rabbitmq/rabbitmq-server#500 is done but we decided to move client ID tracking to Raft. This may or may not happen by 3.8. If not then 3.9 is a natural release to include this as this plugin will be rearchitected. We provide no ETA promises.

**Comment by hairyhum** [comment] 2019-04-25 18:23
@michaelklishin why should it be done with raft? Is there any link to discussion about that?

**Comment by michaelklishin** [comment] 2019-04-25 18:51
It has to be cluster-wide. The MQTT 3.1 spec does not mention any consistency expectations (of course) but most people expect something stronger than eventual. Raft is a good option that we already use.

**Comment by michaelklishin** [comment] 2019-06-10 22:33
Addressed in #195.

**Closed** 2019-06-10 22:33 UTC
Labels: bug, effort-medium, enhancement
