### ISSUE TITLE
mqtt plugin "duplicate client id" 

### ISSUE THREAD

**Issue by panjunDev** [rabbitmq/rabbitmq-mqtt#193] opened 2019-04-13 14:44 UTC
hi,friend
I have used rabbitmq for my MQTT broker In the past few months,but recently i find a issue, that is "if a client start more than one connection request and those requests be routed to same rabbitmq node ,this node will hint 'MQTT disconnecting duplicate client id' and close some duplicate connection,finally one clientId just have one connection .But if those requests  be routed to different nodes,one clientId will have  multiple connections,that's bad",here is my network topology:
client->nginx->rabbitmq cluster(three nodes)

Here is my nginx config:
upstream ts_rabbitmq_backend {
        server 10.200.46.92:1883;
        server 10.200.46.94:1883;
        server 10.200.41.28:1883;
}

Client  use nginx address start a connection,and nginx random route connection to one of rabbitmq nodes. 

What i should do this?

thks!

**Comment by michaelklishin** [comment] 2019-04-13 19:09
Duplicate of #91.

**Closed by michaelklishin** 2019-04-13 19:09 UTC

**Comment by michaelklishin** [comment] 2019-04-13 19:10
We plan on making client ID tracking clusterwide. No ETA promises but the latest it can happen is 3.9. Right now you can avoid depending on unique client IDs or store them e.g. in a service such as etcd or Consul, since the problem most users solve with it is that of consumer coordination.
